version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend/src/main/kotlin/com/dynam
    command: ["kotlin", "LibraryInstallerKt", "your_library_name"]
    depends_on:
      - python

  python:
    image: python:3.9
    volumes:
      - ./python:/app/python
    working_dir: /app/python
    command: ["python3", "pop_general.py", "your_library_name"]